# Generated by Django 2.1.2 on 2018-10-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181017_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studiengang',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='vorname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='nachname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='matrikelnummer',
            new_name='matriculation_number',
        ),
    ]
