# Generated by Django 2.1.2 on 2018-10-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181017_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
    ]
