# Generated by Django 2.1.2 on 2018-10-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=255)),
                ('nachname', models.CharField(max_length=255)),
                ('matrikelnummer', models.IntegerField()),
                ('studiengang', models.CharField(max_length=2)),
                ('semester', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
