# Generated by Django 2.1.2 on 2018-10-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='matrikelnummer',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
